from django.db import models


class User(models.Model):
    id = models.BigIntegerField(primary_key=True)
    id_str = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    screen_name = models.CharField(max_length=255)
    location = models.CharField(max_length=255, blank=True)
    url = models.URLField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    protected = models.BooleanField()
    followers_count = models.IntegerField()
    friends_count = models.IntegerField()
    listed_count = models.IntegerField()
    created_at = models.DateTimeField()
    favourites_count = models.IntegerField()
    utc_offset = models.IntegerField(blank=True, null=True)
    time_zone = models.CharField(max_length=255, blank=True, null=True)
    geo_enabled = models.BooleanField()
    verified = models.BooleanField()
    statuses_count = models.IntegerField()
    lang = models.CharField(max_length=255)
    contributors_enabled = models.BooleanField()
    is_translator = models.BooleanField()
    is_translation_enabled = models.BooleanField()
    profile_background_color = models.CharField(max_length=255)
    profile_background_image_url = models.URLField()
    profile_background_image_url_https = models.URLField()
    profile_background_tile = models.BooleanField()
    profile_image_url = models.URLField()
    profile_image_url_https = models.URLField()
    profile_link_color = models.CharField(max_length=255)
    profile_sidebar_border_color = models.CharField(max_length=255)
    profile_sidebar_fill_color = models.CharField(max_length=255)
    profile_text_color = models.CharField(max_length=255)
    profile_use_background_image = models.BooleanField()
    default_profile = models.BooleanField()
    default_profile_image = models.BooleanField()
    following = models.BooleanField(blank=True, null=True)
    follow_request_sent = models.BooleanField(blank=True, null=True)
    notifications = models.BooleanField(blank=True, null=True)


class Tweet(models.Model):
    created_at = models.DateTimeField()
    id = models.BigIntegerField(primary_key=True)
    id_str = models.CharField(max_length=255)
    text = models.TextField()
    source = models.CharField(max_length=255)
    truncated = models.BooleanField()
    in_reply_to_status_id = models.BigIntegerField(blank=True, null=True)
    in_reply_to_status_id_str = models.CharField(max_length=255, blank=True, null=True)
    in_reply_to_user_id = models.BigIntegerField(blank=True, null=True)
    in_reply_to_user_id_str = models.CharField(max_length=255, blank=True, null=True)
    in_reply_to_screen_name = models.CharField(max_length=255, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    geo = models.CharField(max_length=255, blank=True, null=True)
    coordinates = models.CharField(max_length=255, blank=True, null=True)
    place = models.CharField(max_length=255, blank=True, null=True)
    contributors = models.CharField(max_length=255, blank=True, null=True)
    retweet_count = models.IntegerField()
    favorite_count = models.IntegerField()
    favorited = models.BooleanField()
    retweeted = models.BooleanField()
    possibly_sensitive = models.BooleanField()
    filter_level = models.CharField(max_length=255)
    lang = models.CharField(max_length=255)
