# Generated by Django 5.0.7 on 2024-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tweet_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='contributors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='geo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
    ]
